### PR TITLE
remove link ticket container to let pack get rid of link tickets

### PR DESCRIPTION
**Pull request by jimfulton**

### CODE REVIEW

**Comment by jimfulton** [comment]
This evolution has been applied to stage.

**Comment by pauleveritt** [comment]
Make sure to look in the osi customization package. That's the thing that does the importing. https://github.com/karlhosting/osi

**Comment by jimfulton** [comment]
I misunderstood the situation. I didn't realize that external links were still exposed in the UI. So I guess that needs to be addressed first.

**Comment by jimfulton** [comment]
Actually, no. I can't find references to LinkTicket or external_link_ticket in either the osi or karl projects.  karl.external_link_ticket.models.ticket.LinkTicket(s) is provided by a separate project/egg.

a) IDK what you mean by "importing" and
b) I have no idea what I'm looking for.

Help!

**Comment by pauleveritt** [comment]
It’s not in the UI. It only appears in an include:

https://github.com/karlhosting/osi/blob/master/osi/configure.zcml#L5 <https://github.com/karlhosting/osi/blob/master/osi/configure.zcml#L5>

—Paul

**Comment by jimfulton** [comment]
OK, pack done in stage.

There were 3658502 ZODB records before, there are 3655994 now.

There were 529276 records before, there are 527498 now.

No space was freed, because Postgres databases never get smaller.   

I might have freed space using a full vacuum. I tried and got an error having to do with an index.  I think this is related to an annoying Postgres bug.  I gave up.

**Comment by jimfulton** [comment]
I think this PR should be merged.  I'd like to apply the evolution to prod before Saturday night's pack.

**Comment by jimfulton** [comment]
Oh, and the stage database no-longer contains LinkTicket(s) objects.

**Pull request merged**
