### PR TITLE
Use files from dev-buildout to make this project a buildout

### PR DESCRIPTION
**Pull request by jimfulton**
This PR combines this repo with the dev-buildout repo which should be retired when this is merged.

Note this drops mr.developer support, which could perhaps be added back.  I flailed a bit to make this work and mr.developer was a victim.  Honestly, mr.developer doesn't really buy much.  (The reason for the flailage was a bit of poison in setup.cfg.)

This is part of an effort to unify dev, stage and prod.

### CODE REVIEW

**Comment by jimfulton** [comment]
Any comments on this?

**Comment by jimfulton** [comment]
I have a comment. :)  It need a little more work,

**Comment by jimfulton** [comment]
It wasn't using a develop egg for karl. Fixing that.

**Comment by jimfulton** [comment]
WRT mr.developer, it would be pretty easy to add back support, I think.

**Comment by jimfulton** [comment]
fixed, but since I'm about to do some karl work, let me play with this for a few days.

**Comment by jimfulton** [comment]
This has worked out well for me in the development I've been doing lately.

**Comment by jimfulton** [comment]
When I did this originally, I did it in a bit of a hurry, because I thought I was blocking @pauleveritt .  I removed some of the mr.developer configuration because of that.

I think it would be easy to add mr.developer back. Let me know if you want me to do that. Otherwise, we should remove some left-over mr.developer bits.

Aside from not wanting work to rot, I think this has potential to speed your deployment efforts by leveraging download and egg caches.

**Comment by pauleveritt** [comment]
I think I'd like to get this all digested and in use in the next few weeks, barring @chrisrossi saying hold off until he's wrapped up his stuff. I've made enough mistakes in the past 2 years playing Baby's First DevOps and several of my chronic mistakes get taken care of on this.

**Pull request merged**
