### PR TITLE
Begin the migration to Newt DB by adding a newt tag to the  configuration, causing the newt table to be updated.

### PR DESCRIPTION
**Pull request by jimfulton**
This should get merged and tagged before the prod deployment on Sunday.

This has already been deployed to staging.

### CODE REVIEW

**Comment by jimfulton** [comment]
Oops, I just remembered something important.

**Comment by jimfulton** [comment]
I'd forgotten to specify a transformation function. Fixed.

(It was hardcoded in prototype zodb/json thing.)

**Comment by jimfulton** [comment]
Can this be merged now?

**Comment by pauleveritt** [comment]
Yep. Feels good to have this prepped to go out.

—Paul

**Pull request merged**
